# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches: ["main"]
    paths-ignore:
      - "*.svg"
      - "README.md"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN || secrets.GITHUB_TOKEN }}
          user: ZGQ-inc
          template: classic
          base: header, activity, community, repositories, metadata
          base_hireable: yes
          config_octicon: yes
          config_timezone: Asia/Shanghai
          config_twemoji: yes
          plugin_calendar: yes
          plugin_calendar_limit: 10
          repositories_forks: yes