# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches: ["main"]
    paths-ignore:
      - "*.svg"
      - "README.md"

jobs:
  github-metrics:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - name: Fix AppArmor for Puppeteer
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0 || true

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ZGQ-inc
          template: classic
          base: header, activity, community, repositories, metadata
          base_hireable: yes
          config_octicon: yes
          config_timezone: Asia/Shanghai
          repositories_forks: yes